// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVg7zNqBZcu9T7EAdaEM83QRvWVPgd0G4',
    appId: '1:556033310301:web:3ad4b2fa2c58e22286d7b4',
    messagingSenderId: '556033310301',
    projectId: 'fir-rtdb-ce819',
    authDomain: 'fir-rtdb-ce819.firebaseapp.com',
    databaseURL: 'https://fir-rtdb-ce819-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-rtdb-ce819.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsebMPj9rI9_Ec44qAYXcrPVgWNO-E7Lc',
    appId: '1:556033310301:android:295f2653da78762a86d7b4',
    messagingSenderId: '556033310301',
    projectId: 'fir-rtdb-ce819',
    databaseURL: 'https://fir-rtdb-ce819-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-rtdb-ce819.firebasestorage.app',
  );
}
